"use client";

import { useState } from "react";
import { Footer, Header, SectionLabel } from "../components";

export default function PricingPage() {
  const [blocks,setBlocks] = useState(1);
  const [waste,setWaste] = useState(false);
  const total = blocks * 219 + (waste ? 28 : 0);
  return <main><Header /><section className="inner-hero"><SectionLabel number="Tarifs">Transparents avant de réserver</SectionLabel><h1>Des prix simples, <em>calculés avant de réserver.</em></h1><p>Le temps constitue la base. Les déchets et besoins exceptionnels sont affichés séparément, avant le paiement.</p></section><section className="pricing-layout"><div className="pricing-principles"><article><span>01</span><h2>Le temps</h2><p>1/2 journée · 4 h<br />1 journée · 8 h</p></article><article><span>02</span><h2>Les travaux</h2><p>Le matériel standard est inclus. Un besoin spécifique est toujours signalé.</p></article><article><span>03</span><h2>Les déchets</h2><p>Leur évacuation peut être ajoutée directement dans la réservation.</p></article><article><span>04</span><h2>Le déplacement</h2><p>Inclus dans notre zone principale autour de Brignoles.</p></article></div><div className="pricing-calc"><span>Mini-calculateur</span><h2>Votre estimation</h2><label>Durée<select value={blocks} onChange={(e)=>setBlocks(Number(e.target.value))}><option value="1">1/2 journée — 4 h</option><option value="2">1 journée — 8 h</option><option value="3">1,5 jour — 12 h</option></select></label><label className="calc-check"><input type="checkbox" checked={waste} onChange={(e)=>setWaste(e.target.checked)} />Évacuer environ 1–2 m³ de déchets</label><div><small>Total TTC</small><strong>{total} €</strong><p>≈ {Math.ceil(total/2)} € après crédit d’impôt*</p></div><a className="button button-light" href="/reserver">Configurer précisément →</a></div></section><section className="tax-explainer" id="fiscalite"><SectionLabel number="Fiscalité" light>Services à la personne</SectionLabel><h2>Le crédit d’impôt n’est pas <em>une remise commerciale.</em></h2><p>Les prestations d’entretien courant éligibles peuvent ouvrir droit à un crédit d’impôt de 50 %, dans la limite réglementaire. Les fournitures et prestations non éligibles restent affichées séparément. L’éligibilité dépend de votre situation et du cadre légal applicable.</p><div><span>Total TTC <b>280 €</b></span><span>Part éligible <b>220 €</b></span><span>Crédit potentiel <b>110 €</b></span><strong>Reste à charge estimé <b>170 €</b></strong></div></section><Footer /></main>;
}
